using System.Collections;
using System;
using UnityEngine;
using System.Linq;
using UnityEngine.UI;
using System.Collections.Generic;

public enum BattleAction
{
    Skill,
    SwitchPokemon,
    UseItem,
    Run
}
public enum BattleState
{
    None,
    Start,
    Action,
    Skill,
    RunningTurn,
    Busy,
    PartyScreen,
    SkillToForget,
    ConfirmBox,
    Evolution,
    BattleOver,
    ConfigSelection,
    Dialog
}
public class BattleSystem : MonoBehaviour
{
    public static BattleSystem Inst;
    [SerializeField] public BattleUnit playerUnit;
    [SerializeField] public BattleUnit enemyUnit;
    BattleDialogBox dialogBox;
    // [SerializeField] ConfigPanel configPanel;
    [SerializeField] GameObject Pokeball;
    // [SerializeField] GameObject ConfirmBox;

    //Party
    // [SerializeField] PartyScreen partyScreen;
    // [SerializeField] SkillSelectScreen skillSelectScreen;

    // [HideInInspector] public static BattleState state;
    BattleState preState;
    // int currentAction = 0;
    // int currentSkill = 0;
    // int currentMember = 0;
    // int currentSelection = 0;
    // int currentConfirm = 0;
    int escapeAttempts = 0;

    PokemonParty playerParty;
    PokemonParty trainerParty;
    Pokemon wildPokemon;
    bool isTrainerBattle = false;

    PlayerCtrl player;
    Image PlayerImage;
    TrainerCtrl trainer;

    SkillBase skillToLearn;

    private void Awake()
    {
        Inst = this;

        player = GameManager.Inst.playerCtrl;
        dialogBox = GameManager.Inst.dialogBox;
    }
    private void Start()
    {
        // state = BattleState.Start;
        // currentAction = 0;
        // PlayerImage.sprite = player.TrainerSprite;
        // PlayerImage.gameObject.SetActive(false);
    }
    public void StartBattle(PokemonParty playerParty, Pokemon wildPokemon)
    {
        GameManager.state = BattleState.Start;
        isTrainerBattle = false;
        this.playerParty = playerParty;
        this.wildPokemon = wildPokemon;
        StartCoroutine(SetUpBattle());
    }
    public void StartTrainerBattle(PokemonParty playerParty, PokemonParty trainerParty)
    {
        this.playerParty = playerParty;
        this.trainerParty = trainerParty;

        isTrainerBattle = true;

        player = playerParty.GetComponent<PlayerCtrl>();
        trainer = trainerParty.GetComponent<TrainerCtrl>();

        StartCoroutine(SetUpBattle());
    }
    /*
    public void Update()
    {
        if (state == BattleState.BattleOver || state == BattleState.Evolution)
        {
            return;
        }
        if (state == BattleState.ActionSelection)
        {
            HandleActionSelection();
        }
        else if (state == BattleState.SkillSelection)
        {
            HandleSkillSelection();
        }
        else if (state == BattleState.PartyScreen)
        {
            HandlePartyScreenSelection();
        }
        else if (state == BattleState.SkillToForget)
        {
            HandleLearnSkillSelection();
        }
        else if (state == BattleState.ConfirmBox)
        {
            HandleConfirmBoxSelection();
        }

        if (Input.GetKeyDown(KeyCode.Escape))
        {
            if (state == BattleState.ConfigSelection)
            {
                if (configPanel.state == ConfigState.Config_Right)
                {
                    if (Input.GetKeyDown(KeyCode.Escape))
                    {
                        configPanel.gameObject.SetActive(false);
                        state = preState;
                    }
                }
            }
            else
            {
                configPanel.gameObject.SetActive(true);
                preState = state;
                state = BattleState.ConfigSelection;
            }
        }
        if (Input.GetKeyDown(KeyCode.G))
        {
            Debug.Log(currentMember);
        }
        if (Input.GetKeyDown(KeyCode.F))
        {
            Debug.Log(playerUnit.BattlePokemon.Attack);
            Debug.Log(playerUnit.BattlePokemon.Rankup[0]);
        }
        if (Input.GetKeyDown(KeyCode.T))
        {
            Debug.Log($"{playerUnit.BattlePokemon.PokemonGen}");
        }
    }
*/
    public IEnumerator SetUpBattle()
    {
        if (isTrainerBattle == false)
        {
            playerUnit.SetUp(playerParty.GetHealthyPokemon());
            enemyUnit.SetUp(wildPokemon);

            dialogBox.SetSkillNames(playerUnit.BattlePokemon.Skills);
            GameManager.Inst.skillCount = playerUnit.BattlePokemon.Skills.Count;
            yield return dialogBox.TypeDialog($"ì•—! ì•¼ìƒ {enemyUnit.BattlePokemon.P_Base.PokemonName}{GetCorrectParticle(enemyUnit.BattlePokemon.P_Base.PokemonName, "subject")} \níŠ€ì–´ë‚˜ì™”ë‹¤!");
        }
        else
        {
            playerUnit.gameObject.SetActive(false);
            enemyUnit.gameObject.SetActive(false);

            PlayerImage.gameObject.SetActive(true);
            // PlayerImage.gameObject.SetActive(true);

            PlayerImage.sprite = player.TrainerSprite;
            // PlayerImage.sprite = trainer.TrainerSprite;

            yield return dialogBox.TypeDialog($"{trainer.TrainerName}{/*ì€ëŠ”ì´ê°€*/""}ì´ ë°°í‹€ì„ ê±¸ì–´ì™”ë‹¤!");
        }
        escapeAttempts = 0;
        GameManager.Inst.partyScreen.Init();
        GameManager.Inst.ActionSelection();
    }
    void BattleOver(bool won)
    {
        if (GameManager.state == BattleState.Dialog)
        {
            StartCoroutine(new WaitUntil(() => GameManager.state != BattleState.Dialog));
            GameManager.state = BattleState.BattleOver;
        }
        GameManager.state = BattleState.BattleOver;
        StopAllCoroutines();
        GameManager.Inst.EndBattle(won);
    }
    void ChooseSkillToForget(Pokemon pokemon, SkillBase newSkill)
    {
        GameManager.state = BattleState.Busy;
        StartCoroutine(dialogBox.TypeDialog($"ì–´ëŠ ê¸°ìˆ ì„ ìŠê²Œ í•˜ê³ ì‹¶ì€ê°€?"));
        GameManager.Inst.skillSelectScreen.gameObject.SetActive(true);
        GameManager.Inst.skillSelectScreen.SetPokemonData(pokemon);
        GameManager.Inst.skillSelectScreen.SetSkill(pokemon.Skills.Select(x => x.SkillBase).ToList(), newSkill);
        skillToLearn = newSkill;

        GameManager.state = BattleState.SkillToForget;
    }

    #region BattleSystem
    public IEnumerator RunTurns(BattleAction playerAction)
    {
        GameManager.state = BattleState.RunningTurn;
        if (playerAction == BattleAction.Skill)
        {
            playerUnit.BattlePokemon.CurrentSkill = playerUnit.BattlePokemon.Skills[GameManager.Inst.currentSkill];
            enemyUnit.BattlePokemon.CurrentSkill = enemyUnit.BattlePokemon.GetRandomSkill();

            if (playerUnit.BattlePokemon.CurrentSkill == null || enemyUnit.BattlePokemon.CurrentSkill == null)
            {
                yield break;
            }
            int playerPriority = playerUnit.BattlePokemon.CurrentSkill.SkillBase.Priority;
            int enemyPriority = enemyUnit.BattlePokemon.CurrentSkill.SkillBase.Priority;

            int playerSpeed = playerUnit.BattlePokemon.Speed;
            int enemySpeed = enemyUnit.BattlePokemon.Speed;

            Debug.Log($"ğŸ•Šï¸ í”Œë ˆì´ì–´ ìŠ¤í‚¬ ìš°ì„ ë„: {playerPriority}, ì†ë„: {playerSpeed}");
            Debug.Log($"ğŸ ì  ìŠ¤í‚¬ ìš°ì„ ë„: {enemyPriority}, ì†ë„: {enemySpeed}");

            // ìŠ¤í”¼ë“œ ì²´í¬
            bool playerTurnFirst = true;
            //ìš°ì„ ë„ ì²´í¬
            if (enemyPriority > playerPriority)
            {
                playerTurnFirst = false;
            }
            else if (playerPriority == enemyPriority)
            {
                if (playerSpeed == enemySpeed)
                {
                    playerTurnFirst = UnityEngine.Random.Range(0, 2) == 0;
                }
                else
                {
                    playerTurnFirst = playerSpeed > enemySpeed;
                }
            }

            var firstUnit = playerTurnFirst ? playerUnit : enemyUnit;
            var secondUnit = playerTurnFirst ? enemyUnit : playerUnit;

            var targetOfFirst = secondUnit;
            var targetOfSecond = firstUnit;

            // 1. ì„ ê³µì í–‰ë™
            yield return RunSkill(firstUnit, targetOfFirst, firstUnit.BattlePokemon.CurrentSkill);
            yield return RunAfterTrun(firstUnit);

            if (GameManager.state == BattleState.BattleOver)
            {
                yield break;
            }
            // ì„ ê³µìê°€ ê³µê²©í•œ ëŒ€ìƒ ì“°ëŸ¬ì§ í™•ì¸
            if (targetOfFirst.BattlePokemon == null || targetOfFirst.BattlePokemon.PokemonHp <= 0)
            {
                Debug.Log("â›” ë’¤ì§");
                yield return HandlePokemonFainted(targetOfFirst);
                yield return CheckForBattleOver(targetOfFirst);
                yield break;
            }

            // 2. í›„ê³µì í–‰ë™ (ìê¸°ì™€ ëŒ€ìƒ ëª¨ë‘ ì‚´ì•„ ìˆì„ ë•Œë§Œ)
            if (secondUnit.BattlePokemon != null && secondUnit.BattlePokemon.PokemonHp > 0 && targetOfSecond.BattlePokemon != null && targetOfSecond.BattlePokemon.PokemonHp > 0)
            {
                yield return RunSkill(secondUnit, targetOfSecond, secondUnit.BattlePokemon.CurrentSkill);
                yield return RunAfterTrun(secondUnit);

                if (GameManager.state == BattleState.BattleOver)
                {
                    yield break;
                }
                if (targetOfSecond.BattlePokemon != null && targetOfSecond.BattlePokemon.PokemonHp <= 0)
                {
                    yield return HandlePokemonFainted(targetOfSecond);
                    yield return CheckForBattleOver(targetOfSecond);
                    yield break;
                }
            }
            else
            {
                Debug.Log("â›” í›„ê³µì ë˜ëŠ” ëŒ€ìƒì´ ì“°ëŸ¬ì§„ ìƒíƒœ. í›„ê³µ í–‰ë™ ìƒëµ.");
                yield break;
            }
        }
        //ìŠ¤í‚¬ ì™¸ í–‰ë™
        else
        {
            Debug.Log($"â–¶ í”Œë ˆì´ì–´ê°€ {playerAction} ì„ íƒ");

            if (playerAction == BattleAction.SwitchPokemon)
            {
                var selectedPokemon = playerParty.Party[GameManager.Inst.currentMember];
                preState = BattleState.RunningTurn;
                GameManager.state = BattleState.Busy;
                yield return SwitchPokemon(selectedPokemon);
            }
            else if (playerAction == BattleAction.UseItem)
            {
                preState = GameManager.state;
                GameManager.state = BattleState.Busy;
                dialogBox.EnableActionSelector(false);
                yield return ThrowPokeball();
            }
            else if (playerAction == BattleAction.Run)
            {
                preState = GameManager.state;
                GameManager.state = BattleState.Busy;
                yield return TryToRun();
            }

            if (GameManager.state == BattleState.BattleOver)
            {
                Debug.Log("ğŸ ì•„ì´í…œ/êµì²´/ë„ë§ í›„ ì „íˆ¬ ì¢…ë£Œë¨");
                yield break;
            }

            // ì  í„´
            var enemySkill = enemyUnit.BattlePokemon.GetRandomSkill();

            if (enemyUnit.BattlePokemon == null || enemyUnit.BattlePokemon.PokemonHp <= 0)
            {
                Debug.LogWarning("â— ì  í¬ì¼“ëª¬ì´ ì“°ëŸ¬ì¡ŒìŒ. ì  í„´ ìŠ¤í‚µ.");
            }
            else
            {
                yield return RunSkill(enemyUnit, playerUnit, enemySkill);
                yield return RunAfterTrun(enemyUnit);

                if (GameManager.state == BattleState.BattleOver)
                {
                    Debug.Log("ğŸ ì  í„´ ì¢…ë£Œ í›„ ì „íˆ¬ ì¢…ë£Œë¨");
                }

                if (playerUnit.BattlePokemon.PokemonHp <= 0)
                {
                    Debug.Log("âš ï¸ í”Œë ˆì´ì–´ í¬ì¼“ëª¬ ì“°ëŸ¬ì§");
                    yield return HandlePokemonFainted(playerUnit);
                    yield return CheckForBattleOver(playerUnit);
                    yield break;
                }
            }
        }

        //ê³„ì† í„´ ì§„í–‰
        if (GameManager.state != BattleState.BattleOver)
        {
            // Debug.Log("âœ… RunTurns ì¢…ë£Œ");
            GameManager.Inst.ActionSelection();
        }
    }
    IEnumerator RunSkill(BattleUnit sourceUnit, BattleUnit targetUnit, Skill skill)
    {
        bool canRunSkill = sourceUnit.BattlePokemon.OnBeforeSkill();
        if (canRunSkill == false)
        {
            yield return ShowStatusChanges(sourceUnit.BattlePokemon);
            yield return sourceUnit.BattleHud.UpdateHp();
            yield break;
        }
        yield return ShowStatusChanges(sourceUnit.BattlePokemon);

        //ê³µê²© ì• ë‹ˆë©”ì´ì…˜
        skill.PP--;

        yield return dialogBox.TypeDialog($"{sourceUnit.BattlePokemon.P_Base.PokemonName}ì˜ {skill.SkillBase.SkillName}!");
        if (CheckSkillHits(skill, sourceUnit.BattlePokemon, targetUnit.BattlePokemon))
        {
            //ë³€í™”ê¸° ì²˜ë¦¬
            if (skill.SkillBase.CategoryKey == CategoryKey.Status)
            {
                //ì¤‘ë³µ ìƒíƒœì´ìƒ ì²´í¬
                if (targetUnit.BattlePokemon.Status != null)
                {
                    yield return dialogBox.TypeDialog("íš¨ê³¼ê°€ ì—†ëŠ” ê²ƒ ê°™ë‹¤...");
                }
                else
                {
                    yield return RunSkillEffects(skill.SkillBase.Effects, sourceUnit.BattlePokemon, targetUnit.BattlePokemon, skill.SkillBase.Target);
                }
            }
            else
            {
                //í”¼ê²© ì• ë‹ˆë©”ì´ì…˜
                targetUnit.PlayHitAnimation();
                var (startHp, endHp, damageDetails) = targetUnit.BattlePokemon.TakeDamage(skill, sourceUnit.BattlePokemon);

                StartCoroutine(targetUnit.BattleHud.UpdateHp());
                yield return ShowDamageDetails(damageDetails);
            }
            //ì¶”ê°€íš¨ê³¼ ì¡´ì¬ ì‹œ
            if (skill.SkillBase.SecondaryEffects != null && skill.SkillBase.SecondaryEffects.Count > 0 && targetUnit.BattlePokemon.PokemonHp > 0)
            {
                foreach (var secondary in skill.SkillBase.SecondaryEffects)
                {
                    var rnd = UnityEngine.Random.Range(1, 101);
                    if (rnd <= secondary.Chance)
                    {
                        yield return RunSkillEffects(secondary, sourceUnit.BattlePokemon, targetUnit.BattlePokemon, secondary.Target);
                    }
                }
            }
            if (targetUnit.BattlePokemon.PokemonHp <= 0)
            {
                yield return HandlePokemonFainted(targetUnit);
            }
        }
        else
        {
            if (sourceUnit.IsPlayerUnit)
            {
                yield return dialogBox.TypeDialog($"ìƒëŒ€ {targetUnit.BattlePokemon.P_Base.PokemonName}ì—ê²ŒëŠ” \në§ì§€ ì•Šì•˜ë‹¤!");
            }
            else
            {
                yield return dialogBox.TypeDialog($"{targetUnit.BattlePokemon.P_Base.PokemonName}ì—ê²ŒëŠ” ë§ì§€ ì•Šì•˜ë‹¤!");
            }
        }
    }
    IEnumerator RunAfterTrun(BattleUnit sourceUnit)
    {
        if (GameManager.state == BattleState.BattleOver)
        {
            yield break;
        }

        yield return new WaitUntil(() => GameManager.state == BattleState.RunningTurn);
        yield return new WaitForSeconds(1.2f);

        sourceUnit.BattlePokemon.OnAfterTurn();

        yield return ShowStatusChanges(sourceUnit.BattlePokemon);
        yield return sourceUnit.BattleHud.UpdateHp();

        //ìƒíƒœì´ìƒ ë°ë¯¸ì§€ë¡œ ì£½ìœ¼ë©´ @@@@
        if (sourceUnit.BattlePokemon.PokemonHp <= 0)
        {
            yield return HandlePokemonFainted(sourceUnit);
            yield return new WaitUntil(() => GameManager.state == BattleState.RunningTurn);
            // yield return dialogBox.TypeDialog($"{sourceUnit.BattlePokemon.PokemonBase.PokemonName}{GetCorrectParticle(sourceUnit.BattlePokemon.PokemonBase.PokemonName, false)} ì“°ëŸ¬ì¡Œë‹¤!");
            // /*
            // ì‚¬ë§ ì• ë‹ˆë©”ì´ì…˜ ì¬ìƒ

            // */

            // yield return new WaitForSeconds(2.0f);
        }

        yield return new WaitForSeconds(1.0f);

    }
    //ìƒíƒœì´ìƒ, ë­í¬ì—… ì²˜ë¦¬
    IEnumerator RunSkillEffects(SkillEffects effects, Pokemon sourceUnit, Pokemon targetUnit, SkillTarget skillTarget)
    {
        //RankUp
        if (effects.Rankup != null)
        {
            if (skillTarget == SkillTarget.Self)
            {
                sourceUnit.ApplyRankups(effects.Rankup);
            }
            else
            {
                targetUnit.ApplyRankups(effects.Rankup);
            }
        }
        //ìƒíƒœì´ìƒ
        if (effects.Status != ConditionID.None)
        {
            targetUnit.SetStatus(effects.Status);
        }
        //ì¼ì‹œ ìƒíƒœì´ìƒ
        if (effects.VolatileStatus != ConditionID.None)
        {
            targetUnit.SetVolatileStatus(effects.VolatileStatus);
        }

        yield return ShowStatusChanges(sourceUnit);
        yield return ShowStatusChanges(targetUnit);
    }
    //ëª…ì¤‘ë¥  ê³„ì‚°
    bool CheckSkillHits(Skill skill, Pokemon source, Pokemon target)
    {
        if (skill.SkillBase.AlwaysHits)
        {
            return true;
        }
        float SkillAccuracy = skill.SkillBase.SkillAccuracy;
        int accuracy = source.Rankup[Stat.Accuracy];
        int evasion = target.Rankup[Stat.Evasion];

        var rankupValues = new float[] { 1f, 1.5f, 2f, 2.5f, 3f, 3.5f, 4f };

        if (accuracy > 0)
        {
            SkillAccuracy *= rankupValues[accuracy];
        }
        else
        {
            SkillAccuracy /= rankupValues[-accuracy];
        }
        if (evasion > 0)
        {
            SkillAccuracy /= rankupValues[evasion];
        }
        else
        {
            SkillAccuracy *= rankupValues[-evasion];
        }


        return UnityEngine.Random.Range(1, 101) <= SkillAccuracy;
    }
    //ë­í¬ì—… ë©”ì‹œì§€ ì¶œë ¥
    IEnumerator ShowStatusChanges(Pokemon pokemon)
    {
        while (pokemon.StatusCngMsg.Count > 0)
        {
            string message = pokemon.StatusCngMsg.Dequeue();
            yield return dialogBox.TypeDialog(message);
        }
    }
    IEnumerator HandlePokemonFainted(BattleUnit faintedUnit)
    {
        yield return dialogBox.TypeDialog($"{faintedUnit.BattlePokemon.P_Base.PokemonName}{GetCorrectParticle(faintedUnit.BattlePokemon.P_Base.PokemonName, "topic")} ì“°ëŸ¬ì¡Œë‹¤!");
        //ì‚¬ë§ ì• ë‹ˆë©”ì´ì…˜ ì¬ìƒ @@@@
        yield return new WaitForSeconds(1.5f);
        //í”Œë ˆì´ì–´ ìŠ¹ë¦¬
        if (!faintedUnit.IsPlayerUnit)
        {
            int expYield = faintedUnit.BattlePokemon.P_Base.ExpYield;
            int enemyLevel = faintedUnit.BattlePokemon.PokemonLevel;
            float trainerBonus = (isTrainerBattle) ? 1.5f : 1.0f;

            int expGain = Mathf.FloorToInt(expYield * enemyLevel * trainerBonus / 7);
            playerUnit.BattlePokemon.PokemonExp += expGain;
            yield return playerUnit.BattleHud.SetExpSmooth();
            yield return dialogBox.TypeDialog($"{playerUnit.BattlePokemon.P_Base.PokemonName}{GetCorrectParticle(playerUnit.BattlePokemon.P_Base.PokemonName, "topic")}\n{expGain}ê²½í—˜ì¹˜ë¥¼ ì–»ì—ˆë‹¤!");
            yield return CheckLearnableSkill();
        }
        yield return CheckForBattleOver(faintedUnit);
        GameManager.Inst.AddGold();
    }
    public IEnumerator SwitchPokemon(Pokemon newPokemon)
    {
        playerUnit.BattlePokemon.CureVolatileStatus();
        playerUnit.BattlePokemon.ResetRankup();

        yield return dialogBox.TypeDialog($"ëŒì•„ì™€ {playerUnit.BattlePokemon.P_Base.PokemonName}!");
        //ê·€í™˜ ì• ë‹ˆë©”ì´ì…˜@@@

        yield return new WaitForSeconds(1.5f);

        // í˜„ì¬ ì „íˆ¬ ì¤‘ì¸ í¬ì¼“ëª¬ (ì¸ë±ìŠ¤ 0ì— ìˆëŠ” í¬ì¼“ëª¬)
        var currentBattlePokemon = playerParty.Party[0];

        // êµì²´ ì‘ì—…: êµì²´í•  í¬ì¼“ëª¬ì„ 0ë²ˆ ì¸ë±ìŠ¤ë¡œ, ë‚˜ê°€ìˆëŠ” í¬ì¼“ëª¬ì„ êµì²´í•  í¬ì¼“ëª¬ì˜ ì¸ë±ìŠ¤ë¡œ ì´ë™
        playerParty.Party[0] = newPokemon;
        playerParty.Party[GameManager.Inst.currentMember] = currentBattlePokemon;

        playerUnit.SetUp(newPokemon);
        dialogBox.SetSkillNames(newPokemon.Skills);

        GameManager.Inst.skillCount = newPokemon.Skills.Count;

        yield return dialogBox.TypeDialog($"ê°€ë! {newPokemon.P_Base.PokemonName}!");
        GameManager.state = preState;
    }
    [HideInInspector] public bool cancelSelected = false;
    IEnumerator CheckLearnableSkill()
    {
        while (playerUnit.BattlePokemon.CheckForLevelUp())
        {
            playerUnit.BattleHud.SetLevel();
            yield return dialogBox.TypeDialog($"{playerUnit.BattlePokemon.P_Base.PokemonName}{GetCorrectParticle(playerUnit.BattlePokemon.P_Base.PokemonName, "topic")} ë ˆë²¨ {playerUnit.BattlePokemon.PokemonLevel}ë¡œ ì˜¬ëë‹¤!");

            var newSkill = playerUnit.BattlePokemon.GetLearnableSkill();
            if (newSkill != null)
            {
                if (playerUnit.BattlePokemon.Skills.Count < PokemonBase.MaxNumOfSkills)
                {
                    playerUnit.BattlePokemon.LearnSkill(newSkill);
                    yield return dialogBox.TypeDialog($"{playerUnit.BattlePokemon.P_Base.PokemonName}{GetCorrectParticle(playerUnit.BattlePokemon.P_Base.PokemonName, "topic")} ìƒˆë¡œ {newSkill.SkillBase.SkillName}{GetCorrectParticle(newSkill.SkillBase.SkillName, "object")} ë°°ì› ë‹¤!");
                    dialogBox.SetSkillNames(playerUnit.BattlePokemon.Skills);
                }
                else
                {
                    bool isFinalDecisionMade = false;
                    while (!isFinalDecisionMade)
                    {
                        yield return dialogBox.TypeDialog($"{playerUnit.BattlePokemon.P_Base.PokemonName}{GetCorrectParticle(playerUnit.BattlePokemon.P_Base.PokemonName, "topic")} ìƒˆë¡œ {newSkill.SkillBase.SkillName}{GetCorrectParticle(newSkill.SkillBase.SkillName, "object")} ë°°ìš°ê³  ì‹¶ì–´í•œë‹¤!");
                        yield return dialogBox.TypeDialog($"í•˜ì§€ë§Œ ê¸°ìˆ ì´ 4ê°œì´ë¯€ë¡œ ë‹¤ë¥¸ ê¸°ìˆ ì„ ìŠì–´ì•¼ í•œë‹¤.");
                        yield return dialogBox.TypeDialog($"{newSkill.SkillBase.SkillName} ëŒ€ì‹  ë‹¤ë¥¸ ê¸°ìˆ ì„ ìŠê²Œ í•˜ê² ìŠµë‹ˆê¹Œ?");

                        GameManager.Inst.ConfirmBoxSelection();
                        yield return new WaitUntil(() => GameManager.state != BattleState.ConfirmBox);
                        bool isConfirmed = GameManager.Inst.HandleConfirmBoxSelection();

                        if (isConfirmed)
                        {
                            ChooseSkillToForget(playerUnit.BattlePokemon, newSkill.SkillBase);
                            yield return new WaitUntil(() => GameManager.state == BattleState.Busy);

                            if (cancelSelected || GameManager.Inst.currentSelection == PokemonBase.MaxNumOfSkills)
                            {
                                cancelSelected = false;

                                yield return dialogBox.TypeDialog($"ê·¸ëŸ¼... {newSkill.SkillBase.SkillName}{GetCorrectParticle(newSkill.SkillBase.SkillName, "object")} ë°°ìš°ëŠ” ê²ƒì„ í¬ê¸°í•˜ê² ìŠµë‹ˆê¹Œ?");
                                GameManager.Inst.ConfirmBoxSelection();
                                yield return new WaitUntil(() => GameManager.state != BattleState.ConfirmBox);
                                bool giveUp = GameManager.Inst.HandleConfirmBoxSelection();

                                if (giveUp)
                                {
                                    yield return dialogBox.TypeDialog($"{playerUnit.BattlePokemon.P_Base.PokemonName}{GetCorrectParticle(playerUnit.BattlePokemon.P_Base.PokemonName, "topic")} ê²°êµ­ {newSkill.SkillBase.SkillName}{GetCorrectParticle(newSkill.SkillBase.SkillName, "object")} ë°°ìš°ì§€ ì•Šì•˜ë‹¤!");
                                    skillToLearn = null;
                                    isFinalDecisionMade = true;
                                }
                                else
                                {
                                    ChooseSkillToForget(playerUnit.BattlePokemon, newSkill.SkillBase);
                                    yield return new WaitUntil(() => GameManager.state == BattleState.SkillToForget);
                                }
                            }
                            else
                            {
                                var oldSkill = playerUnit.BattlePokemon.Skills[GameManager.Inst.currentSelection].SkillBase;
                                playerUnit.BattlePokemon.Skills[GameManager.Inst.currentSelection] = new Skill(newSkill.SkillBase);

                                yield return dialogBox.TypeDialog("1, 2, ... ì§ !");
                                yield return dialogBox.TypeDialog($"{playerUnit.BattlePokemon.P_Base.PokemonName}{GetCorrectParticle(playerUnit.BattlePokemon.P_Base.PokemonName, "topic")} {oldSkill.SkillName}{GetCorrectParticle(oldSkill.SkillName, "object")} ê¹¨ë—ì´ ìŠì—ˆë‹¤!");
                                yield return dialogBox.TypeDialog($"ê·¸ë¦¬ê³  {newSkill.SkillBase.SkillName}{GetCorrectParticle(newSkill.SkillBase.SkillName, "object")} ë°°ì› ë‹¤!");

                                dialogBox.SetSkillNames(playerUnit.BattlePokemon.Skills);
                                skillToLearn = null;
                                isFinalDecisionMade = true;
                            }
                        }
                        else
                        {
                            yield return dialogBox.TypeDialog($"ê·¸ëŸ¼... {newSkill.SkillBase.SkillName}{GetCorrectParticle(newSkill.SkillBase.SkillName, "object")} ë°°ìš°ëŠ” ê²ƒì„ í¬ê¸°í•˜ê² ìŠµë‹ˆê¹Œ?");
                            GameManager.Inst.ConfirmBoxSelection();
                            yield return new WaitUntil(() => GameManager.state != BattleState.ConfirmBox);
                            bool isReallyConfirmed = GameManager.Inst.HandleConfirmBoxSelection();

                            if (isReallyConfirmed)
                            {
                                yield return dialogBox.TypeDialog($"{playerUnit.BattlePokemon.P_Base.PokemonName}{GetCorrectParticle(playerUnit.BattlePokemon.P_Base.PokemonName, "topic")} ê²°êµ­ {newSkill.SkillBase.SkillName}{GetCorrectParticle(newSkill.SkillBase.SkillName, "object")} ë°°ìš°ì§€ ì•Šì•˜ë‹¤!");
                                skillToLearn = null;
                                isFinalDecisionMade = true;
                            }
                        }
                    }
                }
            }

            yield return playerUnit.BattleHud.SetExpSmooth(true);
        }
    }
    IEnumerator CheckForBattleOver(BattleUnit faintedUnit)
    {
        if (faintedUnit.IsPlayerUnit)
        {
            var nextPokemon = playerParty.GetHealthyPokemon();
            if (nextPokemon != null)
            {
                preState = GameManager.state;
                GameManager.Inst.OpenPartyScreen();
            }
            else
            {
                BattleOver(false);
            }
        }
        else
        {
            //ì•¼ìƒí¬ì¼“ëª¬
            if (!isTrainerBattle)
            {
                yield return playerParty.CheckForEvolutions();
                yield return new WaitForSeconds(0.5f); // ì§„í™” ë§ˆë¬´ë¦¬ ëŒ€ê¸°
                BattleOver(true);
            }
            else
            {
                var nextPokemon = trainerParty.GetHealthyPokemon();
                if (nextPokemon != null)
                {
                    //ë‹¤ìŒí¬ì¼€
                    yield return playerParty.CheckForEvolutions();

                }
                else
                {
                    yield return playerParty.CheckForEvolutions();

                    BattleOver(true);
                }
            }
        }
    }
    IEnumerator ShowDamageDetails(DamageDetails damageDetails)
    {
        if (damageDetails.Critical > 1f)
        {
            yield return dialogBox.TypeDialog("ê¸‰ì†Œì— ë§ì•˜ë‹¤!");
        }
        if (damageDetails.TypeEffectiveness > 1)
        {
            if (damageDetails.TypeEffectiveness > 2)
            {
                yield return dialogBox.TypeDialog("íš¨ê³¼ê°€ êµ‰ì¥í–ˆë‹¤!!");
            }
            else
            {
                yield return dialogBox.TypeDialog("íš¨ê³¼ê°€ ëŒ€ë‹¨í–ˆë‹¤!");
            }
        }

        else if (damageDetails.TypeEffectiveness < 1f)
        {
            if (damageDetails.TypeEffectiveness == 0)
            {
                yield return dialogBox.TypeDialog("íš¨ê³¼ê°€ ì—†ëŠ” ë“¯ í•˜ë‹¤...");
            }
            else
            {
                yield return dialogBox.TypeDialog("íš¨ê³¼ê°€ ë³„ë¡œì¸ë“¯ í•˜ë‹¤...");
            }
        }
    }
    #endregion
    #region Catch
    IEnumerator ThrowPokeball()
    {
        if (isTrainerBattle)
        {
            yield return dialogBox.TypeDialog("ë‹¤ë¥¸ íŠ¸ë ˆì´ë„ˆì˜ í¬ì¼“ëª¬ì€ ì¡ì„ ìˆ˜ ì—†ë‹¤!");
            GameManager.state = preState;
            yield break;
        }

        var pokeballObj = Instantiate(Pokeball, playerUnit.transform.position, Quaternion.identity);
        var pokeball = pokeballObj.GetComponent<SpriteRenderer>();

        //#34 1254
        //pokeball.transform.DoMove

        int shakeCount = TryToCatchPokemon(enemyUnit.BattlePokemon);
        for (int i = 0; i < Math.Min(shakeCount, 3); ++i)
        {
            yield return new WaitForSeconds(0.5f);
            //í”ë“¤ê¸° ì• ë‹ˆë©”ì´ì…˜
        }
        if (shakeCount == 4)
        {
            //ì¡í˜
            playerParty.AddPokemon(enemyUnit.BattlePokemon);

            GlobalValue.CatchPokemon(enemyUnit.BattlePokemon.P_Base, false);

            Destroy(pokeball);
            yield return dialogBox.TypeDialog($"ì‹ ë‚œë‹¤-!\nì•¼ìƒ {enemyUnit.BattlePokemon.P_Base.PokemonName}ì„ ì¡ì•˜ë‹¤!");
            BattleOver(true);
        }
        else
        {
            yield return dialogBox.TypeDialog($"ì•ˆì¡í˜!");
            Destroy(pokeball);
            GameManager.state = preState;
        }
        yield return new WaitForSeconds(1.0f);
    }
    int TryToCatchPokemon(Pokemon pokemon)
    {
        float a = (3 * pokemon.MaxHp - 2 * pokemon.PokemonHp) * pokemon.P_Base.CatchRate * ConditionsDB.GetStatusBonus(pokemon.Status) / (3 * pokemon.MaxHp);

        if (a >= 255)
        {
            //í”ë“¤ë¦° íšŸìˆ˜
            return 4;
        }

        float b = 1048560 / Mathf.Sqrt(Mathf.Sqrt(16711680 / a));

        int shakeCount = 0;
        while (shakeCount < 4)
        {
            if (UnityEngine.Random.Range(0, 65535) >= b)
            {
                break;
            }
            ++shakeCount;
        }
        return shakeCount;
    }
    #endregion

    IEnumerator TryToRun()
    {
        if (isTrainerBattle)
        {
            yield return dialogBox.TypeDialog("íŠ¸ë ˆì´ë„ˆ ë°°í‹€ ì¤‘ ë„ë§ x");
            GameManager.state = preState;
            yield break;
        }

        ++escapeAttempts;
        int playerSpeed = playerUnit.BattlePokemon.Speed;
        int enemySpeed = enemyUnit.BattlePokemon.Speed;

        if (enemySpeed <= playerSpeed)
        {
            yield return dialogBox.TypeDialog("ë¬´ì‚¬íˆ ë„ë§ì³¤ë‹¤!");
            BattleOver(true);
        }
        else
        {
            float f = (playerSpeed * 128) / (enemySpeed + 30 * escapeAttempts);
            f = f % 256;

            if (UnityEngine.Random.Range(0, 256) < f)
            {
                yield return dialogBox.TypeDialog("ë¬´ì‚¬íˆ ë„ë§ì³¤ë‹¤!");
                BattleOver(true);
            }
            else
            {
                yield return dialogBox.TypeDialog("ë„ë§ì¹  ìˆ˜ ì—†ì—ˆë‹¤!");
                GameManager.state = preState;
            }
        }
    }


    string GetCorrectParticle(string name, string particleType)    //ì€ëŠ”ì´ê°€
    {
        char lastChar = name[name.Length - 1];
        int unicode = (int)lastChar;
        bool endsWithConsonant = (unicode - 44032) % 28 != 0; // 44032ëŠ” 'ê°€'ì˜ ìœ ë‹ˆì½”ë“œ, 28ëŠ” ë°›ì¹¨ì˜ ìˆ˜


        switch (particleType)
        {
            case "subject": // ì´/ê°€
                { return endsWithConsonant ? "ì´" : "ê°€"; }
            case "topic": // ì€/ëŠ”
                { return endsWithConsonant ? "ì€" : "ëŠ”"; }
            case "object": // ì„/ë¥¼
                { return endsWithConsonant ? "ì„" : "ë¥¼"; }
            case "objectTo": // ë¡œ/ìœ¼ë¡œ
                { return endsWithConsonant ? "ë¡œ" : "ìœ¼ë¡œ"; }
            default:
                throw new ArgumentException("Invalid particle type");
        }
    }
}
